language: ruby
before_install:
  - git submodule update --init --recursive
bundler_args: --without development
script: "bundle exec rake build"
rvm:
  - 1.9.3
gemfile:
  - Gemfile
branches:
  only:
    - master
